[platformio]
description = Teensy 4.1 on-target unit tests

[common]
extra_scripts = extra_script.py
build_unflags = -std=gnu++14 -std=c++14 -std=gnu++17 -std=c++17

[env:teensy41_test_sensors]
platform = teensy
board = teensy41
framework = arduino
upload_protocol = custom
upload_command = tycmd upload $SOURCE
test_framework = unity
test_filter = test_sensors
test_speed = 115200
test_build_src = yes
lib_ldf_mode = chain
extra_scripts = ${common.extra_scripts}
build_unflags = ${common.build_unflags}
build_flags =
  -Isrc
  -Isrc/utils
  -Isrc/comms
  -Isrc/sensors
  -std=gnu++20
  -DUSB_SERIAL
  -Wno-volatile
lib_deps =
  adafruit/Adafruit ICM20X
  ssilverman/QNEthernet
  Wire
  SPI
build_src_filter =
  -<*>
  +<sensors/buff_encoder.cpp>
  +<sensors/ICM20649.cpp>
  +<sensors/StereoCamTrigger.cpp>
  +<comms/comms_layer.cpp>
  +<comms/ethernet_comms.cpp>
  +<comms/data/>
  +<comms/config_data/>

[env:teensy41_test_fltrs]
platform = teensy
board = teensy41
framework = arduino
upload_protocol = custom
upload_command = tycmd upload $SOURCE
test_framework = unity
test_filter = test_fltrs
test_speed = 115200
test_build_src = yes
extra_scripts = ${common.extra_scripts}
build_unflags = ${common.build_unflags}
build_flags =
  -Isrc
  -Isrc/utils
  -std=gnu++20
  -DUSB_SERIAL
  -Wno-volatile
build_src_filter =
  -<*>
  +<filters/pid_filter.cpp>
  +<filters/lowpass_filter.cpp>

[env:teensy41_test_utils]
platform = teensy
board = teensy41
framework = arduino
upload_protocol = custom
upload_command = tycmd upload $SOURCE
test_framework = unity
test_filter = test_utils
test_speed = 115200
test_build_src = yes
extra_scripts = ${common.extra_scripts}
build_unflags = ${common.build_unflags}
build_flags =
  -Isrc
  -Isrc/utils
  -std=gnu++20
  -DUSB_SERIAL
  -Wno-volatile
build_src_filter =
  -<*>
  +<utils/wrapping.cpp>
  +<utils/vector_math.cpp>

[env:teensy41_test_cntrls]
platform = teensy
board = teensy41
framework = arduino
upload_protocol = custom
upload_command = tycmd upload $SOURCE
test_framework = unity
test_filter = test_cntrls
test_speed = 115200
test_build_src = yes
lib_ldf_mode = chain
extra_scripts = ${common.extra_scripts}
build_unflags = ${common.build_unflags}
build_flags =
  -Isrc
  -Isrc/utils
  -Isrc/comms
  -Isrc/controls
  -Isrc/sensors
  -Isrc/sensors/can
  -std=gnu++20
  -fconcepts
  -DUSB_SERIAL
  -Wno-volatile
lib_deps =
  adafruit/Adafruit ICM20X
  Wire
  SPI
build_src_filter =
  -<*>
  +<controls/controller.cpp>
  +<utils/wrapping.cpp>
  +<utils/vector_math.cpp>