[platformio]
description = Teensy 4.1 on-target unit tests

[env:teensy41_test]
platform = teensy
board = teensy41
framework = arduino
upload_protocol = teensy-cli
test_framework = unity
test_speed = 115200
test_build_src = yes
build_flags =
  -Isrc
  -DUSB_SERIAL
build_src_filter =
  -<*>
  +<utils/wrapping.cpp>
  +<utils/vector_math.cpp>
