#pragma once
#include <stdint.h>
#include "comms/data/comms_data.hpp" // for CommsData, TypeLabel,

/// @note Do not edit this file unless you are aware of the implications of doing so. The enums and data structs 

namespace Cfg {
/// @brief StateName is a unique identifier for every possible robot state that we want to estimate and control.
enum class StateName : uint32_t {
    Unset,
    ChassisX,
    ChassisY,
    ChassisHeading,
    GimbalYaw,
    GimbalPitch,
    Flywheels,
    Feeder,

    StateNameCount
};

/// @brief StateOrder is the order of the state 
enum class StateOrder : uint32_t {
    Position,
    Velocity,
    Acceleration,
};

struct ReferenceLimit {
    float min;
    float max;
};

struct ReferenceLimits {
    ReferenceLimit position;
    ReferenceLimit velocity;
    ReferenceLimit acceleration;
};

struct State : Comms::CommsData {
    ReferenceLimits reference_limits;
    StateOrder governor_type;
    uint32_t is_wrapping;
    StateName name;
};

};